apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ls-web.fullname" . }}
  {{- with .Values.app.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    role: nginx
    {{- include "ls-web.labels" . | nindent 4 }}
    {{- if .Values.app.labels }}
    {{- toYaml .Values.app.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "ls-app.selectorLabels" . | nindent 6 }}
  {{- with .Values.app.deploymentStrategy }}
  strategy:
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.app.annotations }}
      annotations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      labels:
        role: nginx
        {{- include "ls-app.selectorLabels" . | nindent 8 }}
        {{- if .Values.app.podLabels }}
        {{- toYaml .Values.app.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ls-app.serviceAccountName" . }}
      {{- if .Values.app.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.app.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.app.automountServiceAccountToken }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      containers:
        - name: nginx
          image: "{{ .Values.global.image.repository }}-web:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if .Values.app.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.app.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args: {{-  range .Values.app.nginx.args }}
            - {{ . }}
          {{- end }}
          env:
            - name: APP_HOST
              value: {{ include "ls-app.fullname" . }}.{{ .Release.Namespace }}.svc
            {{- include "ls.common.envs" . | nindent 12}}
            {{- if .Values.app.nginx.extraEnvironmentVars -}}
            {{- range $key, $value := .Values.app.nginx.extraEnvironmentVars }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.app.nginx.extraEnvironmentSecrets -}}
            {{- range $key, $value := .Values.app.nginx.extraEnvironmentSecrets }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
            {{- end }}
          ports:
            - name: {{ .Values.app.service.portName }}
              containerPort: 8085
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'sleep {{ .Values.app.preStopDelaySeconds }}' ]
          {{- if .Values.app.nginx.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: "{{ if eq .Values.app.contextPath "/" }}{{ .Values.app.nginx.readinessProbe.path }}{{ else }}{{ .Values.app.contextPath }}{{ .Values.app.nginx.readinessProbe.path }}{{ end }}"
              port: 8085
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.app.nginx.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: "{{ if eq .Values.app.contextPath "/" }}{{ .Values.app.nginx.livenessProbe.path }}{{ else }}{{ .Values.app.contextPath }}{{ .Values.app.nginx.livenessProbe.path }}{{ end }}"
              port: 8085
            failureThreshold: {{ .Values.app.nginx.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.app.nginx.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.nginx.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.nginx.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.nginx.livenessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /label-studio/data
            {{- if .Values.app.extraVolumeMounts }}
              {{ toYaml .Values.app.extraVolumeMounts | nindent 12 }}
            {{- end }}
            - mountPath: /opt/heartex/instance-data/etc
              name: opt-heartex-nginx
            - mountPath: /tmp
              name: tmp-dir-nginx
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.app.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "tplvalues.render" (dict "value" .Values.app.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.app.dnsPolicy }}
      enableServiceLinks: {{ .Values.app.enableServiceLinks }}
      shareProcessNamespace: {{ .Values.app.shareProcessNamespace }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if and .Values.global.persistence.enabled (eq .Values.global.persistence.type "volume") }}
          persistentVolumeClaim:
            claimName: {{ include "ls-pvc.claimName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if and .Values.global.persistence.enabled (eq .Values.global.persistence.type "gcs") }}
        {{- if or .Values.global.persistence.config.gcs.applicationCredentialsJSON (and .Values.global.persistence.config.gcs.applicationCredentialsJSONExistingSecret .Values.global.persistence.config.gcs.applicationCredentialsJSONExistingSecretKey) }}
        - name: gcs-storage-credentials
          secret:
            {{- if and .Values.global.persistence.config.gcs.applicationCredentialsJSONExistingSecret .Values.global.persistence.config.gcs.applicationCredentialsJSONExistingSecretKey }}
            secretName: {{ .Values.global.persistence.config.gcs.applicationCredentialsJSONExistingSecret }}
            {{- else }}
            secretName: {{ include "ls-secrets.fullname" . }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.global.pgConfig.ssl.pgSslSecretName }}
        - name: pg-ssl-certs
          secret:
            secretName: {{ include "render-values" ( dict "value" .Values.global.pgConfig.ssl.pgSslSecretName "context" $) }}
            defaultMode: 0640
        {{- end }}
        {{- if .Values.global.redisConfig.ssl.redisSslSecretName }}
        - name: redis-ssl-certs
          secret:
            secretName: {{ include "render-values" ( dict "value" .Values.global.redisConfig.ssl.redisSslSecretName "context" $) }}
            defaultMode: 0640
        {{- end }}
        {{- if .Values.app.extraVolumes -}}
          {{- toYaml .Values.app.extraVolumes | nindent 8 }}
        {{- end }}
        - name: opt-heartex-nginx
          emptyDir: { }
        - name: tmp-dir-nginx
          emptyDir: { }
